FROM php:8.0-fpm

RUN apt-get update && \
    apt-get install -y \
        libpng-dev \
        libzip-dev \
        zip \
        libmagickwand-dev \
        --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
        exif \
        mysqli \
        gd \
        zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
