FROM php:8.2-fpm@sha256:3f5a4480edeba66b07e12233e0c7cdac91b4c3b6997cdae4af06c6926fa5ec70

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev \
    libevent-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg-dev \
    libldap2-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libpng-dev \
    libpq-dev \
    libxml2-dev \
    libmagickwand-dev \
    libzip-dev \
    libwebp-dev \
    libgmp-dev && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp

RUN docker-php-ext-install \
    bcmath \
    exif \
    gd \
    intl \
    ldap \
    opcache \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    zip \
    gmp

RUN pecl install \
    APCu \
    memcached \
    redis \
    imagick

RUN docker-php-ext-enable \
    apcu \
    memcached \
    redis \
    imagick && \
    rm -r /tmp/pear

ADD ./www.conf /usr/local/etc/php-fpm.d/www.conf
