name: build-image

inputs:
  REGISTRY:
    required: false
    default: docker.io
  IMAGE_NAME:
    required: true
  IMAGE_TAG:
    required: false
    default: latest
  CONTEXT_PATH:
    required: false
    default: .
  REG_USER:
    required: true
  REG_PASS:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        docker build -t ${{ inputs.REGISTRY }}/${{ inputs.REG_USER }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} ${{ inputs.CONTEXT_PATH }}
        docker login -u ${{ inputs.REG_USER }} -p ${{ inputs.REG_PASS }} ${{ inputs.REGISTRY }}
        docker push ${{ inputs.REGISTRY }}/${{ inputs.REG_USER }}/${{ inputs.IMAGE_NAME }} --all-tags
