FROM php:8.3-fpm@sha256:261139b5c72b28423d9d68541f62357a517a87dbcc0f771570e6b23c9639043a

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    libmagickwand-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    exif \
    mysqli \
    gd \
    zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
