FROM php:8.3-fpm@sha256:76cd9c45c8c01d8d2eb26f28d3e06bb109b45b40010fba763f1dba55949ac768

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    libmagickwand-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    exif \
    mysqli \
    gd \
    zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
