FROM php:8.3-fpm@sha256:7404314f9db06301e7b80d5fb5f80ef2266eac2f98f515ef84305c5de54de32a

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    libmagickwand-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    exif \
    mysqli \
    gd \
    zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
