FROM php:8.2-fpm@sha256:f57933cbc65c1c0939c880840fbd6a9929ffee3746ed14390dd5646cc474469f

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    libmagickwand-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    exif \
    mysqli \
    gd \
    zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
