FROM php:8.2-fpm@sha256:faf32167826a68cb7c595793e2e508164a24cac187be60ed8de9c81b17236048

RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    libzip-dev \
    zip \
    libmagickwand-dev \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install \
    exif \
    mysqli \
    gd \
    zip && \
    printf "\n" | pecl install imagick && \
    docker-php-ext-enable imagick
