name: build-image

on:
  workflow_call:
    inputs:
      REGISTRY:
        type: string
        required: true
      IMAGE_NAME:
        type: string
        required: true
      IMAGE_TAG:
        type: string
        required: true
      CONTEXT_PATH:
        type: string
        required: true
    secrets:
      REG_USER:
        required: true
      REG_PASS:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Image ${{ inputs.IMAGE_NAME }} erstellen
        run: docker build -t ${{ inputs.REGISTRY }}/${{ secrets.REG_USER }}/${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} ${{ inputs.CONTEXT_PATH }}

      - name: Bei ${{ inputs.REGISTRY }} anmelden
        run: docker login -u ${{ secrets.REG_USER }} -p ${{ secrets.REG_PASS }} ${{ inputs.REGISTRY }}

      - name: Image ${{ inputs.IMAGE_NAME }} pushen
        run: docker push ${{ inputs.REGISTRY }}/${{ secrets.REG_USER }}/${{ inputs.IMAGE_NAME }} --all-tags
